create table if not exists nsgl_account_chartns_tree(
ns_set_id integer not null,
nsgl_account_id integer null,
ns_tree_effective_date varchar(255) null,
ns_tree_code integer null,
ns_tree_description varchar(255) null,
ns_level1 varchar(255) null,
ns_level1_desc varchar(255) null,
ns_level2 varchar(255) null,
ns_level2_desc varchar(255) null,
ns_level3 varchar(255) null,
ns_level3_desc varchar(255) null,
ns_level4 varchar(255) null,
ns_level4_desc varchar(255) null,
ns_level5 varchar(255) null,
ns_level5_desc varchar(255) null,
ns_level6 varchar(255) null,
ns_level6_desc varchar(255) null,
ns_level7 varchar(255) null,
ns_level7_desc varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint nsgl_account_chartns_tree_pk primary key(ns_set_id));